//Exercise #1

When a Mule app starts, a connectivity test runs on components (such as the HTTP or FTP connector) that need to connect to an external server. If the test fails, instead of blocking the deployment, the default behavior is to log a warning message and continue with the deployment of the app.

You can modify this behavior by setting a designated number of reconnection attempts, if you encounter a failure. You can also force the deployment to fail if all connection attempts fail.

* Fails Deployment (`failsDeployment`): Forces the deployment to fail if the connection fails and all configured reconnection attempts are exhausted. This is an attribute of `<reconnection/>`.
* Reconnect (`reconnect`): Limits the number of reconnection attempts and sets the time intervals between their execution. For example, you might set a count of 5 reconnection attempts at a frequency of every 4000 milliseconds (ms). This function defaults to 2 reconnection attempts at a frequency of 2000 ms.
* The example below is a code snippet where deployment fails after 5 failed reconnection attempts (each attempt is 4000 ms apart):

[source,xml]
----
<http:request-config name="HTTP_Request_Config" doc:name="HTTP Request Config">
  <http:request-connection host="https://jsonplaceholder.typicode.com/posts" port="80">
    <reconnection failsDeployment="true">
      <reconnect frequency="4000" count="5"/>
    </reconnection>
  </http:request-connection>
</http:request-config>
----

* Reconnect Forever (`reconnect-forever`): Attempts to reconnect at a given interval, for example, every 4000 ms for as long as the application is running. By default, the reconnection attempts will occur every 2000 ms. No value for count is specified or needed since there is no limit on the number of attempts.

* The example below shows `reconnect-forever`, with the interval between reconnection attempts set to 4000 ms:

[source,xml]
----
<http:request-connection host="https://jsonplaceholder.typicode.com/posts" port="80" >
  <reconnection>
    <reconnect-forever frequency="4000"/>
  </reconnection>
</http:request-connection>
----
